### ISSUE TITLE
现在还能用吗

### ISSUE THREAD

**Issue by liuwar** [IKkSssDendi/fg_show_web#1]
执行了下好像缺一些依赖，抖音数据部分是不是也不能抓取

**Comment by IKkSssDendi** [comment]
> 执行了下好像缺一些依赖，抖音数据部分是不是也不能抓取

之前无聊随便写写的，不要当真，逻辑什么的都设计的很垃圾。抖音那部分根本就没写，docker也没有做，看看图个乐就好 XD
